-- 数据库初始化脚本（MySQL 5.7）
CREATE DATABASE IF NOT EXISTS homework_bg DEFAULT CHARSET=utf8mb4;
USE homework_bg;


-- 播客主表
CREATE TABLE IF NOT EXISTS podcast (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '播客ID',
    content TEXT NOT NULL COMMENT '播客内容摘要',
    voice_ids VARCHAR(255) NOT NULL COMMENT '播客音色素材ID列表，逗号分隔',
    content_type VARCHAR(255) NOT NULL COMMENT '播客内容标签',
    transcript TEXT COMMENT '播客完整脚本',
    title VARCHAR(255) NOT NULL COMMENT '播客标题',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

